export enum WeaponType {
  AXE_1H = 'axe_1h',
  AXE_2H = 'axe_2h',
  BOW = 'bow',
  CROSSBOW = 'crossbow',
  DAGGER = 'dagger',
  FIST = 'fist',
  GUN = 'gun',
  MACE_1H = 'mace_1h',
  MACE_2H = 'mace_2h',
  POLEARM = 'polearm',
  SHIELD = 'shield',
  STAFF = 'staff',
  SWORD_1H = 'sword_1h',
  SWORD_2H = 'sword_2h',
  WAND = 'wand',
  WARGLAIVE = 'warglaive',
  OTHER = 'other',
}
